Update 2cicd_builder.yml

diff --git a/.github/workflows/2cicd_builder.yml b/.github/workflows/2cicd_builder.yml
--- a/.github/workflows/2cicd_builder.yml
+++ b/.github/workflows/2cicd_builder.yml
@@ -24,19 +24,12 @@ on:
       commit_message:
         required: false
         type: string      
-      # image_name:
-      #   required: true
-      #   type: string
       image:
         required: false
         type: string
         default: ubuntu-latest
         
     secrets:
-     # DOCKER_USERNAME:
-     #   required: true
-     # DOCKER_PASSWORD:
-     #   required: true
       AUTH_TOKEN:
         required: true
       TELEGRAM_NOTIFICATION_TOKEN:
@@ -53,14 +46,14 @@ on:
         required: true
       SSH_ACCESS_DEMO_01:
         required: true
-      # GITHUB_TOKEN:
-      #   required: true
         
 permissions:
   contents: read
   packages: write
 
 jobs:         
+
+
 #-------------- TEST RUST ----------------#
   test-rust:
     if: ${{ inputs.language == 'rust' && github.event_name != 'release' && github.event.action != 'published' && inputs.build_version == '' && github.ref_name != 'main' }}
@@ -76,9 +69,6 @@ jobs:
         if: ${{ github.ref_name != 'beta' && github.ref_name != 'main' }}
         uses: actions/cache@v3
         with:
-          # path: |
-          #   target
-          #   .cargo
           path: |
             ~/.cargo/bin/
             ~/.cargo/registry/index/
@@ -106,6 +96,7 @@ jobs:
         with:
           command: test
 
+
 #-------------- TEST C# ----------------#
   test-csharp:
     if: ${{ inputs.language == 'csharp' && github.event_name != 'release' && github.event.action != 'published' && inputs.build_version == '' && github.ref_name != 'main' }}
@@ -127,6 +118,7 @@ jobs:
           dotnet build
           dotnet test
           
+
 #-------------- BUILD RUST ----------------#
   build-rust:
     # if: ${{ (inputs.language == 'rust' && github.event_name == 'release' && github.event.action == 'published') || (inputs.language == 'rust' && inputs.build_version != '' && github.ref_name != 'main') }}
@@ -154,9 +146,6 @@ jobs:
         if: ${{ github.ref_name != 'beta' && github.ref_name != 'main' }}
         uses: actions/cache@v3
         with:
-          # path: |
-          #   target
-          #   .cargo
           path: |
             ~/.cargo/bin/
             ~/.cargo/registry/index/
@@ -179,48 +168,26 @@ jobs:
         uses: arduino/setup-protoc@v3
       - run: openssl version
 
-      # # Install dependencies
-      # - run: sudo apt update
-      #   continue-on-error: true
-      # - run: sudo apt install -y build-essential libglib2.0-dev pkg-config libssl-dev libgtk-3-dev
-      # - run: sudo apt update && sudo apt upgrade -y
-      #   continue-on-error: true
-      # - run: sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 -y
-
       - name: Build project
         run: cargo build --release
 
       - name: List release files
         run: ls -la ./target/release
-        
-      # - name: Build and Push Docker Image
-      #   uses: docker/build-push-action@v1
-      #   with:
-      #     username: ${{ secrets.DOCKER_USERNAME }}
-      #     password: ${{ secrets.DOCKER_PASSWORD }}
-      #     path: .
-      #     registry: docker.io
-      #     repository: ${{ inputs.image_name }}
-      #     tags: ${{ env.VERSION }}
 
-
-
-      # ---------------------- GHCR LOGIN ----------------------
-      - name: Login to GHCR
+      - name: Login to GHCR image registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      # ---------------------- DOCKER BUILD & PUSH ----------------------
       - name: Build and Push
         uses: docker/build-push-action@v5
         with:
-          context: .
-          file: ./Dockerfile
+          context: ./publish-api
           push: true
           tags: ghcr.io/my-prop-trading/${{ inputs.repository_name }}:${{ env.VERSION }}
+
           
   #-------------- BUILD C# ----------------#
   build-csharp:
@@ -272,26 +239,14 @@ jobs:
   
       - name: Check Service dir
         run: ls -la ./publish-api
-          
-      # - name: Build and Push Docker Image
-      #   uses: docker/build-push-action@v1
-      #   with:
-      #     username: ${{ secrets.DOCKER_USERNAME }}
-      #     password: ${{ secrets.DOCKER_PASSWORD }}
-      #     path: ./publish-api
-      #     registry: docker.io
-      #     repository: ${{ inputs.image_name }}
-      #     tags: ${{ env.VERSION }}
 
-      # ---------------------- GHCR LOGIN ----------------------
-      - name: Login to GHCR
+      - name: Login to GHCR image registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      # ---------------------- DOCKER BUILD & PUSH ----------------------
       - name: Build and Push
         uses: docker/build-push-action@v5
         with:
@@ -335,6 +290,7 @@ jobs:
           fi
           echo "VERSION=$VERSION" >> $GITHUB_ENV
           echo "Using version: $VERSION"
+
 
       - name: Deploy to ALPHA
         if: ${{ inputs.service_type == 'server' && github.ref_name != 'beta' && github.ref_name != 'main' && inputs.build_version != '' && github.event_name != 'release' && github.event.action != 'published' }}
@@ -392,6 +348,8 @@ jobs:
             echo "------------ Finished deployment ! ------------"
           EOF
 
+
+
       - name: API Deploy to ALPHA
         if: ${{ inputs.service_type == 'api' && github.ref_name != 'beta' && github.ref_name != 'main' && inputs.build_version != '' && github.event_name != 'release' && github.event.action != 'published' }}
 
@@ -411,24 +369,42 @@ jobs:
             echo "Extracted version: $CURRENT_VERSION"
           fi
           echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
-          
+
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_ALPHA_01 }} << 'EOF'
             echo "------------ Starting API deployment... ------------"
             cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }}
             git pull
-            reg=s"|/${{ inputs.repository_name }}:[0-9].*|/${{ inputs.repository_name }}:${{ env.VERSION }}|g"
-            echo $reg
-            echo "---------------------------------------"
-            find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
-            cat docker-compose.yaml
+
+            # Определяем текущий образ
+            OLD_IMAGE=$(grep -Po "(myproptrading|ghcr.io/my-prop-trading)/${{ inputs.repository_name }}:[0-9].*" *.*ml | tail -n 1)
+            if [[ -z "$OLD_IMAGE" ]]; then
+              echo "Error: unable to find current image"
+              exit 1
+            fi
+            echo "Old image: $OLD_IMAGE"
+
+            # Формируем новый образ
+            if [[ "$OLD_IMAGE" == myproptrading/* ]]; then
+              NEW_IMAGE="ghcr.io/my-prop-trading/${{ inputs.repository_name }}:${{ env.VERSION }}"
+            else
+              NEW_IMAGE=$(echo "$OLD_IMAGE" | sed -r "s/:.*$/:${{ env.VERSION }}/")
+            fi
+            echo "New image: $NEW_IMAGE"
+
+            # Обновляем образ во всех *.*ml файлах
+            find . -type f -name "*.*ml" -exec sed -i -r "s|$OLD_IMAGE|$NEW_IMAGE|g" {} \;
+
+            docker pull $NEW_IMAGE
             docker-compose up -d
+
+            # Коммитим изменения, если что-то изменилось
             if git status | grep -q modified; then
-              # git commit -a -m "Update ${{ inputs.repository_name }}:${{ inputs.build_version }}"
               git commit -a -m "Update ${{ inputs.repository_name }}:${{ env.VERSION }}"
               git push
             fi
-            echo "------------ Finished API deployment ! ------------"
+            echo "------------ Finished deployment ! ------------"
           EOF
+
 
       - name: Deploy to BETA
         if: ${{ inputs.service_type == 'server' && github.ref_name == 'beta' && inputs.build_version != '' && github.event_name != 'release' && github.event.action != 'published' }}
@@ -676,4 +652,4 @@ jobs:
             echo "No jobs failed."
           fi
 
- #--------------------------------------------------------------------------------------------------#     
+ #--------------------------------------------------------------------------------------------------#         
