Update cicd_builder.yml

diff --git a/.github/workflows/cicd_builder.yml b/.github/workflows/cicd_builder.yml
--- a/.github/workflows/cicd_builder.yml
+++ b/.github/workflows/cicd_builder.yml
@@ -283,22 +283,22 @@ jobs:
       # - name: Check dump all context
       #   uses: crazy-max/ghaction-dump-context@v2
 
-      - name: Get current version
-        id: current_version
-        run: |
-          CURRENT_VERSION=$(ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_ALPHA_01 }} << 'EOF'
-            cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }} || { echo "Directory not found"; exit 1; }
-            grep -Po "(?<=test-rs:)[0-9].*" *.*ml || echo "unknown"
-          EOF
-          )
-          CURRENT_VERSION=$(echo "$CURRENT_VERSION" | grep -Eo '[0-9].*' | tail -n 1)
-          if [[ -z "$CURRENT_VERSION" ]]; then
-            echo "Error: Unable to extract current version"
-            exit 1
-          else
-            echo "Extracted version: $CURRENT_VERSION"
-          fi
-          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
+      # - name: Get current version
+      #   id: current_version
+      #   run: |
+      #     CURRENT_VERSION=$(ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_ALPHA_01 }} << 'EOF'
+      #       cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }} || { echo "Directory not found"; exit 1; }
+      #       grep -Po "(?<=${{ inputs.repository_name }}:)[0-9].*" *.*ml || echo "unknown"
+      #     EOF
+      #     )
+      #     CURRENT_VERSION=$(echo "$CURRENT_VERSION" | grep -Eo '[0-9].*' | tail -n 1)
+      #     if [[ -z "$CURRENT_VERSION" ]]; then
+      #       echo "Error: Unable to extract current version"
+      #       exit 1
+      #     else
+      #       echo "Extracted version: $CURRENT_VERSION"
+      #     fi
+      #     echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
 
       - name: Get release version
         id: get_version
@@ -316,6 +316,21 @@ jobs:
         if: ${{ inputs.service_type == 'server' && github.ref_name != 'beta' && github.ref_name != 'main' && inputs.build_version != '' && github.event_name != 'release' && github.event.action != 'published' }}
         run: |
           echo "DEPLOY_ENV=ALPHA" >> $GITHUB_ENV
+
+          CURRENT_VERSION=$(ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_ALPHA_01 }} << 'EOF'
+            cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }} || { echo "Directory not found"; exit 1; }
+            grep -Po "(?<=${{ inputs.repository_name }}:)[0-9].*" *.*ml || echo "unknown"
+          EOF
+          )
+          CURRENT_VERSION=$(echo "$CURRENT_VERSION" | grep -Eo '[0-9].*' | tail -n 1)
+          if [[ -z "$CURRENT_VERSION" ]]; then
+            echo "Error: Unable to extract current version"
+            exit 1
+          else
+            echo "Extracted version: $CURRENT_VERSION"
+          fi
+          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
+          
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_ALPHA_01 }} << 'EOF'
             echo "------------ Starting deployment... ------------"
             cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }}
@@ -340,6 +355,21 @@ jobs:
 
         run: |
           echo "DEPLOY_ENV=ALPHA" >> $GITHUB_ENV
+
+          CURRENT_VERSION=$(ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_ALPHA_01 }} << 'EOF'
+            cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }} || { echo "Directory not found"; exit 1; }
+            grep -Po "(?<=${{ inputs.repository_name }}:)[0-9].*" *.*ml || echo "unknown"
+          EOF
+          )
+          CURRENT_VERSION=$(echo "$CURRENT_VERSION" | grep -Eo '[0-9].*' | tail -n 1)
+          if [[ -z "$CURRENT_VERSION" ]]; then
+            echo "Error: Unable to extract current version"
+            exit 1
+          else
+            echo "Extracted version: $CURRENT_VERSION"
+          fi
+          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
+          
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_ALPHA_01 }} << 'EOF'
             echo "------------ Starting API deployment... ------------"
             cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }}
@@ -364,6 +394,21 @@ jobs:
 
         run: |
           echo "DEPLOY_ENV=BETA" >> $GITHUB_ENV
+
+          CURRENT_VERSION=$(ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_BETA_01 }} << 'EOF'
+            cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }} || { echo "Directory not found"; exit 1; }
+            grep -Po "(?<=${{ inputs.repository_name }}:)[0-9].*" *.*ml || echo "unknown"
+          EOF
+          )
+          CURRENT_VERSION=$(echo "$CURRENT_VERSION" | grep -Eo '[0-9].*' | tail -n 1)
+          if [[ -z "$CURRENT_VERSION" ]]; then
+            echo "Error: Unable to extract current version"
+            exit 1
+          else
+            echo "Extracted version: $CURRENT_VERSION"
+          fi
+          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
+          
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_BETA_01 }} << 'EOF'
             echo "------------ Starting deployment... ------------"
             cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }}
@@ -382,6 +427,21 @@ jobs:
 
         run: |
           echo "DEPLOY_ENV=BETA" >> $GITHUB_ENV
+
+          CURRENT_VERSION=$(ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_BETA_04 }} << 'EOF'
+            cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }} || { echo "Directory not found"; exit 1; }
+            grep -Po "(?<=${{ inputs.repository_name }}:)[0-9].*" *.*ml || echo "unknown"
+          EOF
+          )
+          CURRENT_VERSION=$(echo "$CURRENT_VERSION" | grep -Eo '[0-9].*' | tail -n 1)
+          if [[ -z "$CURRENT_VERSION" ]]; then
+            echo "Error: Unable to extract current version"
+            exit 1
+          else
+            echo "Extracted version: $CURRENT_VERSION"
+          fi
+          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
+          
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_BETA_04 }} << 'EOF'
             echo "------------ Starting API deployment... ------------"
             cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }}
@@ -399,6 +459,21 @@ jobs:
         if: ${{ inputs.service_type == 'server'  && inputs.build_version == '' && github.event_name == 'release' && github.event.action == 'published' }}
         run: |
           echo "DEPLOY_ENV=DEMO" >> $GITHUB_ENV
+
+          CURRENT_VERSION=$(ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_DEMO_01 }} << 'EOF'
+            cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }} || { echo "Directory not found"; exit 1; }
+            grep -Po "(?<=${{ inputs.repository_name }}:)[0-9].*" *.*ml || echo "unknown"
+          EOF
+          )
+          CURRENT_VERSION=$(echo "$CURRENT_VERSION" | grep -Eo '[0-9].*' | tail -n 1)
+          if [[ -z "$CURRENT_VERSION" ]]; then
+            echo "Error: Unable to extract current version"
+            exit 1
+          else
+            echo "Extracted version: $CURRENT_VERSION"
+          fi
+          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
+          
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_DEMO_01 }} << 'EOF'
             echo "------------ Starting deployment... ------------"
             cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }}
@@ -416,6 +491,21 @@ jobs:
         if: ${{ inputs.service_type == 'api'  && inputs.build_version == '' && github.event_name == 'release' && github.event.action == 'published' }}
         run: |
           echo "DEPLOY_ENV=DEMO" >> $GITHUB_ENV
+
+          CURRENT_VERSION=$(ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_DEMO_01 }} << 'EOF'
+            cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }} || { echo "Directory not found"; exit 1; }
+            grep -Po "(?<=${{ inputs.repository_name }}:)[0-9].*" *.*ml || echo "unknown"
+          EOF
+          )
+          CURRENT_VERSION=$(echo "$CURRENT_VERSION" | grep -Eo '[0-9].*' | tail -n 1)
+          if [[ -z "$CURRENT_VERSION" ]]; then
+            echo "Error: Unable to extract current version"
+            exit 1
+          else
+            echo "Extracted version: $CURRENT_VERSION"
+          fi
+          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
+          
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_DEMO_01 }} << 'EOF'
             echo "------------ Starting API deployment... ------------"
             cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }}
